
'''
Author : Junaid Khan 

Blueprint of the state of graph 
each key represents either inut/output in the process of code review workflow

code : raw code that is added in from parser.py --> routes.py  
context : by taking state[code] as imput , query is executed in the retreiver.py to generate context using RAG knowledge base 
security_review,performance_review,style_review,final_review are generated by taking state[code] and state[context] as inputs by style_agent , performance_agent and security_agent , 
finally taking all reviews from agents , aggeregator combines and creates a final review.
'''

from typing import TypedDict, List


class GraphState(TypedDict):

    code: str

    context: str

    security_review: str

    performance_review: str

    style_review: str

    final_review: str